### ISSUE TITLE
Upload converted lectures in go

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live-Worker-v2#14]
Currently, we're using curl to upload lectures. 
We do this because the previous solution 
https://github.com/joschahenningsen/TUM-Live-Worker-v2/blob/efc5d99fa48dc883c137d4a57fba48c8d220f7f2/worker/upload.go#L43
consumed huge amounts of memory for some reason. I assume the video file was loaded into memory unbuffered. 

Since we needed this issue mitigated asap, we had to shell out to curl.

**Comment by Garfield96** [comment]
I'm currently working on a solution based on [https://stackoverflow.com/questions/59191263/how-to-upload-a-gzipped-file-without-reading-everything-into-memory](https://stackoverflow.com/questions/59191263/how-to-upload-a-gzipped-file-without-reading-everything-into-memory)

**Comment by joschahenningsen** [comment]
Amazing!
